version: '3'

services:
  front:
    build: ./front
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
    depends_on:
      - back

  back:
    build: ./back
    restart: always
    ports:
    - "8080:8080"
    environment:
      HOST_DB: db
      PORT: 8080
    networks:
      - back-tier
    depends_on:
      - db

  db:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: 42epitech
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    networks:
      - back-tier

networks:
  back-tier:

volumes:
  db-data:
